// automatically generated by the FlatBuffers compiler, do not modify

package cfg

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Bucket struct {
	_tab flatbuffers.Table
}

func GetRootAsBucket(buf []byte, offset flatbuffers.UOffsetT) *Bucket {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Bucket{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Bucket) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Bucket) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Bucket) BucketName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Bucket) Alias() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func BucketStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func BucketAddBucketName(builder *flatbuffers.Builder, bucketName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(bucketName), 0)
}
func BucketAddAlias(builder *flatbuffers.Builder, alias flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(alias), 0)
}
func BucketEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
