// automatically generated by the FlatBuffers compiler, do not modify

package cfg

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DepCfg struct {
	_tab flatbuffers.Table
}

func GetRootAsDepCfg(buf []byte, offset flatbuffers.UOffsetT) *DepCfg {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DepCfg{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *DepCfg) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DepCfg) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DepCfg) Buckets(obj *Bucket, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *DepCfg) BucketsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *DepCfg) TickDuration() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DepCfg) MutateTickDuration(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *DepCfg) WorkerCount() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DepCfg) MutateWorkerCount(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *DepCfg) Auth() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DepCfg) MetadataBucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DepCfg) SourceBucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func DepCfgStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func DepCfgAddBuckets(builder *flatbuffers.Builder, buckets flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(buckets), 0)
}
func DepCfgStartBucketsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DepCfgAddTickDuration(builder *flatbuffers.Builder, tickDuration uint32) {
	builder.PrependUint32Slot(1, tickDuration, 0)
}
func DepCfgAddWorkerCount(builder *flatbuffers.Builder, workerCount uint32) {
	builder.PrependUint32Slot(2, workerCount, 0)
}
func DepCfgAddAuth(builder *flatbuffers.Builder, auth flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(auth), 0)
}
func DepCfgAddMetadataBucket(builder *flatbuffers.Builder, metadataBucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(metadataBucket), 0)
}
func DepCfgAddSourceBucket(builder *flatbuffers.Builder, sourceBucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(sourceBucket), 0)
}
func DepCfgEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
