// automatically generated by the FlatBuffers compiler, do not modify

package v8init

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Init struct {
	_tab flatbuffers.Table
}

func GetRootAsInit(buf []byte, offset flatbuffers.UOffsetT) *Init {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Init{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Init) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Init) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Init) Appname() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Init) Kvhostport() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Init) Depcfg() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func InitStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func InitAddAppname(builder *flatbuffers.Builder, appname flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(appname), 0)
}
func InitAddKvhostport(builder *flatbuffers.Builder, kvhostport flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(kvhostport), 0)
}
func InitAddDepcfg(builder *flatbuffers.Builder, depcfg flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(depcfg), 0)
}
func InitEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
