// automatically generated by the FlatBuffers compiler, do not modify

package payload

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Payload struct {
	_tab flatbuffers.Table
}

func GetRootAsPayload(buf []byte, offset flatbuffers.UOffsetT) *Payload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Payload{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Payload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Payload) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Payload) Value() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func PayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PayloadAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func PayloadAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(value), 0)
}
func PayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
