#!/bin/bash

export PATH=$PATH:~/bin

rm -rf ~/.ciscripts
git clone -q ssh://github.com/couchbase/eventing ~/.ciscripts
cd ~/.ciscripts
(source ~/.cienv; git checkout unstable)

while true; do
  git pull -q
  find tests/ci -not -name 'build' -and -not -name '.*' -type f -exec cp -v {} ~/bin/ \;
  domain
  (source ~/.cienv; test -f $WORKSPACE/.repo/repo/repo && cp -u $WORKSPACE/.repo/repo/repo ~/bin)
  sleep 600
done

