#!/bin/bash

export PATH=$PATH:~/bin

rm -rf ~/.ciscripts
git clone -q ssh://github.com/couchbase/eventing ~/.ciscripts
cd ~/.ciscripts
(source ~/.cienv; git checkout unstable)

while true; do
  git pull -q
  find tests/ci -not -name 'build' -and -not -name '.*' -type f -exec cp -v {} ~/bin/ \;
  domain
  sleep 600
done

