#!/bin/bash

source ~/.cienv

if [ "$WORKSPACE" = "" ]; then
  echo 'WORKSPACE not set'
  exit 2
fi

if [ "$CIBOT" = "true" ]; then
   sleep 60
   exit 0
fi

for i in {1..240}; do
  upSeconds="$(cat /proc/uptime | grep -o '^[0-9]\+')"
  upHours=$((${upSeconds} / 3600))

  if [ "${upHours}" -gt "24" ]
  then
    sudo reboot
  else
    echo "Uptime less than 24hrs"
  fi

  cd $WORKSPACE
  sleep 60
  current="`git ls-remote git://github.com/couchbase/eventing $BRANCH | awk '{print $1}'`"
  good="`cat ~/eventing.good`"
  if [ "$current" != "$good" ]; then exit 0; fi
done

