#!/bin/bash

source ~/.cienv

if [ "$WORKSPACE" = "" ]; then
  echo 'WORKSPACE not set'
  exit 2
fi

for i in {1..240}; do
  cd $WORKSPACE
  sleep 60
  branch=unstable
  current="`git ls-remote git://github.com/couchbase/eventing $branch | awk '{print $1}'`"
  good="`cat ~/eventing.good`"
  if [ "$current" != "$good" ]; then exit 0; fi
done

