// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_HEADER_FLATBUF_HEADER_H_
#define FLATBUFFERS_GENERATED_HEADER_FLATBUF_HEADER_H_

#include "flatbuffers/flatbuffers.h"

namespace flatbuf {
namespace header {

struct Header;

enum Version {
  Version_Spock = 0,
  Version_MIN = Version_Spock,
  Version_MAX = Version_Spock
};

inline const char **EnumNamesVersion() {
  static const char *names[] = { "Spock", nullptr };
  return names;
}

inline const char *EnumNameVersion(Version e) { return EnumNamesVersion()[static_cast<int>(e)]; }

struct Header FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_VERSION = 4,
    VT_EVENT = 6,
    VT_OPCODE = 8,
    VT_METADATA = 10
  };
  Version version() const { return static_cast<Version>(GetField<int8_t>(VT_VERSION, 0)); }
  int8_t event() const { return GetField<int8_t>(VT_EVENT, 0); }
  int8_t opcode() const { return GetField<int8_t>(VT_OPCODE, 0); }
  const flatbuffers::String *metadata() const { return GetPointer<const flatbuffers::String *>(VT_METADATA); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_VERSION) &&
           VerifyField<int8_t>(verifier, VT_EVENT) &&
           VerifyField<int8_t>(verifier, VT_OPCODE) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_METADATA) &&
           verifier.Verify(metadata()) &&
           verifier.EndTable();
  }
};

struct HeaderBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_version(Version version) { fbb_.AddElement<int8_t>(Header::VT_VERSION, static_cast<int8_t>(version), 0); }
  void add_event(int8_t event) { fbb_.AddElement<int8_t>(Header::VT_EVENT, event, 0); }
  void add_opcode(int8_t opcode) { fbb_.AddElement<int8_t>(Header::VT_OPCODE, opcode, 0); }
  void add_metadata(flatbuffers::Offset<flatbuffers::String> metadata) { fbb_.AddOffset(Header::VT_METADATA, metadata); }
  HeaderBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  HeaderBuilder &operator=(const HeaderBuilder &);
  flatbuffers::Offset<Header> Finish() {
    auto o = flatbuffers::Offset<Header>(fbb_.EndTable(start_, 4));
    return o;
  }
};

inline flatbuffers::Offset<Header> CreateHeader(flatbuffers::FlatBufferBuilder &_fbb,
    Version version = Version_Spock,
    int8_t event = 0,
    int8_t opcode = 0,
    flatbuffers::Offset<flatbuffers::String> metadata = 0) {
  HeaderBuilder builder_(_fbb);
  builder_.add_metadata(metadata);
  builder_.add_opcode(opcode);
  builder_.add_event(event);
  builder_.add_version(version);
  return builder_.Finish();
}

inline flatbuffers::Offset<Header> CreateHeaderDirect(flatbuffers::FlatBufferBuilder &_fbb,
    Version version = Version_Spock,
    int8_t event = 0,
    int8_t opcode = 0,
    const char *metadata = nullptr) {
  return CreateHeader(_fbb, version, event, opcode, metadata ? _fbb.CreateString(metadata) : 0);
}

inline const flatbuf::header::Header *GetHeader(const void *buf) { return flatbuffers::GetRoot<flatbuf::header::Header>(buf); }

inline bool VerifyHeaderBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<flatbuf::header::Header>(nullptr); }

inline void FinishHeaderBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<flatbuf::header::Header> root) { fbb.Finish(root); }

}  // namespace header
}  // namespace flatbuf

#endif  // FLATBUFFERS_GENERATED_HEADER_FLATBUF_HEADER_H_
