// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_PAYLOAD_FBUF_PAYLOAD_H_
#define FLATBUFFERS_GENERATED_PAYLOAD_FBUF_PAYLOAD_H_

#include "flatbuffers/flatbuffers.h"

namespace fbuf {
namespace payload {

struct Payload;

struct Payload FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_KEY = 4,
    VT_VALUE = 6
  };
  const flatbuffers::String *key() const { return GetPointer<const flatbuffers::String *>(VT_KEY); }
  const flatbuffers::String *value() const { return GetPointer<const flatbuffers::String *>(VT_VALUE); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_KEY) &&
           verifier.Verify(key()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_VALUE) &&
           verifier.Verify(value()) &&
           verifier.EndTable();
  }
};

struct PayloadBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_key(flatbuffers::Offset<flatbuffers::String> key) { fbb_.AddOffset(Payload::VT_KEY, key); }
  void add_value(flatbuffers::Offset<flatbuffers::String> value) { fbb_.AddOffset(Payload::VT_VALUE, value); }
  PayloadBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  PayloadBuilder &operator=(const PayloadBuilder &);
  flatbuffers::Offset<Payload> Finish() {
    auto o = flatbuffers::Offset<Payload>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<Payload> CreatePayload(flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> key = 0,
    flatbuffers::Offset<flatbuffers::String> value = 0) {
  PayloadBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_key(key);
  return builder_.Finish();
}

inline flatbuffers::Offset<Payload> CreatePayloadDirect(flatbuffers::FlatBufferBuilder &_fbb,
    const char *key = nullptr,
    const char *value = nullptr) {
  return CreatePayload(_fbb, key ? _fbb.CreateString(key) : 0, value ? _fbb.CreateString(value) : 0);
}

inline const fbuf::payload::Payload *GetPayload(const void *buf) { return flatbuffers::GetRoot<fbuf::payload::Payload>(buf); }

inline bool VerifyPayloadBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<fbuf::payload::Payload>(nullptr); }

inline void FinishPayloadBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<fbuf::payload::Payload> root) { fbb.Finish(root); }

}  // namespace payload
}  // namespace fbuf

#endif  // FLATBUFFERS_GENERATED_PAYLOAD_FBUF_PAYLOAD_H_
