namespace flatbuf.cfg;

table Config {
  app_code:string;
  app_name:string;
  dep_cfg:DepCfg;
  handler_uuid:uint;
  reserved1:uint; // was id
  reserved2:bool; // was usingTimer
  function_instance_id:string;
  reserved3:bool; // was srcMutationEnabled
  access:[string];
  curl:[Curl];
  enforce_schema:bool;
  constants:[Constant];
  lifecycle_state:string;
  version:string;
  owner:Owner;
  function_scope:FunctionScope;
}

table DepCfg {
  buckets:[Bucket];
  metadata_bucket:string;
  source_bucket:string;
  source_scope:string;
  source_collection:string;
  metadata_scope:string;
  metadata_collection:string;
}

table Bucket {
  bucket_name:string;
  alias:string;
  scope_name:string;
  collection_name:string;
}

table Curl {
  hostname:string;
  value:string;
  auth_type:string;
  username:string;
  password:string;
  bearer_key:string;
  allow_cookies:bool;
  validate_ssl_certificate:bool;
}

table Constant {
  value: string;
  literal: string;
}

table Owner {
  uuid:string;
  user:string;
  domain:string;
}

table FunctionScope {
  bucket_name:string;
  scope_name:string;
}

root_type Config;
