namespace flatbuf.cfgv2;

table Config {
  version:int8;
  applocation:AppLocation; // do you need this to store
  app_code:string;
  app_id:uint;
  app_instance_id:string;
  settings:HandlerSetting;
  app_state:AppState;
  deployment_config:DeploymentConfig;
  bindings:[Bindings];
  meta_info:MetaInfo;
  owner:Owner;
}

table Namespace {
  bucket_name:string;
  scope_name:string;
}

table Keyspace {
  bucket_name:string;
  scope_name:string;
  collection_name:string;
}

table AppLocation {
  namespace:Namespace;
  app_name:string;
}

table HandlerSetting {
  cpp_worker_thread:uint32;
  dcp_stream_boundary:string;
  description:string;
  log_level:string;
  num_timer_partition:uint16;
  stats_duration:uint64;
  timer_context_size:uint32;
  worker_count:uint32;
  app_log_dir:string;
  enable_app_rotation:bool;
  app_log_max_size:uint64;
  app_log_max_files:uint32;
  checkpoint_interval:uint64;
  cursor_aware:bool;
  allow_transaction_document:bool;
  allow_sync_document:bool;
  check_interval:uint64;
  max_unacked_bytes:float64;
  max_unacked_count:float64;
  flush_timer:uint64;
  max_parallel_vb:uint16;

  execution_timeout:uint64;
  cursor_checkpoint_timeout:uint64;
  on_deploy_timeout:uint64;
  language_compat:string;
  lcb_inst_capacity:uint32;
  lcb_retry_count:uint32;
  lcb_timeout:uint64;
  n1ql_consistency:string;
  n1ql_prepare:bool;
  handler_header:[string];
  handler_footer:[string];
  bucket_cache_size:uint64;
  bucket_cache_age:uint64;
  curl_resp_size:uint64;
}

table AppState {
  processing_state:bool;
  deployment_state:bool;
}

table DeploymentConfig {
  source_keyspace:Keyspace;
  metadata_keyspace:Keyspace;
}

table Bindings {
  binding_type:uint;
  bucket_binding:BucketBinding;
  curl_binding:CurlBinding;
  constant_binding:ConstantBinding;
}

table KeyspaceInfo {
  uid:string;
  scope_id:string;
  cid:string;
  uuid:string;
  num_vbs:uint16;
}

table MetaInfo {
  request_type:uint8;
  func_id:KeyspaceInfo;
  meta_id:KeyspaceInfo;
  is_using_timer:bool;
  seq:uint32;
  prev_state:string;
  last_paused:string;

  sboundary:string;
  source_id:KeyspaceInfo;
  log_file_name:string;
}

table Owner {
  username:string;
  domain:string;
  uuid:string;
}

table BucketBinding {
  alias:string;
  keyspace:Keyspace;
  access:string;
}

table CurlBinding {
  hostname:string;
  alias:string;
  auth_type:string;
  allow_cookies:bool;
  validate_ssl_certificate:bool;
}

table ConstantBinding {
  literal:string;
  value:string;
}

table SensitiveConfig {
  sensitive:[Sensitive];
}

table Sensitive {
  curl_index:int32;
  username:string;
  password:string;
  bearer_key:string;
}
