#!/bin/bash

APPNAME=$1
PORT=$2
TIMESTAMP=$3

# valgrind --leak-check=full --show-leak-kinds=all --log-file="leak_dump.log" ./client.bin $APPNAME $PORT $TIMESTAMP

./client.bin $APPNAME $PORT $TIMESTAMP &> log
