#!/bin/bash

APPNAME=$1
PORT=$2
WORKERID=$3
BATCHSIZE=$4
LOG_FILE="bin_"$(gdate +%s%N).log

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# valgrind --leak-check=full --show-leak-kinds=all --log-file="leak_dump.log" ./client.bin "$@"

$DIR/client.bin "$@" &> $LOG_FILE
